# Generated by Django 4.2.1 on 2023-05-06 14:29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='标题')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='abc', verbose_name='内容')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻管理',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='标题')),
                ('picture', models.ImageField(upload_to='roll/', verbose_name='图片')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '轮播图管理',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
