# Generated by Django 3.2.18 on 2023-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='标题')),
                ('time', models.CharField(max_length=254, verbose_name='时间')),
                ('href', models.CharField(max_length=254, verbose_name='链接')),
                ('html', models.CharField(max_length=254, verbose_name='前端代码')),
            ],
        ),
        migrations.CreateModel(
            name='roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='序号')),
                ('picture', models.ImageField(upload_to='roll/', verbose_name='轮播图片')),
                ('href', models.CharField(max_length=254, verbose_name='链接')),
            ],
        ),
    ]
