# Generated by Django 3.2.18 on 2023-04-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='html',
            field=models.TextField(verbose_name='前端代码'),
        ),
    ]
