# Generated by Django 3.2.18 on 2023-04-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_news_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='href',
        ),
    ]
