# Generated by Django 3.2.18 on 2023-04-18 16:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_news_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='html',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(default='abc', verbose_name='正文内容'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='title',
            field=models.CharField(max_length=254, verbose_name='标题'),
        ),
    ]
