# Generated by Django 3.2.18 on 2023-04-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230418_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻', 'verbose_name_plural': '所有新闻'},
        ),
        migrations.AlterModelOptions(
            name='roll',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '所有轮播图'},
        ),
    ]
