# Generated by Django 3.2.18 on 2023-04-26 11:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230423_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True, 'verbose_name': '新闻', 'verbose_name_plural': '新闻管理'},
        ),
        migrations.AlterModelOptions(
            name='roll',
            options={'managed': True, 'verbose_name': '图片', 'verbose_name_plural': '轮播图管理'},
        ),
        migrations.RemoveField(
            model_name='roll',
            name='href',
        ),
        migrations.AddField(
            model_name='roll',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='abc', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='picture',
            field=models.ImageField(upload_to='roll/', verbose_name='图片'),
        ),
        migrations.AlterModelTable(
            name='news',
            table='',
        ),
        migrations.AlterModelTable(
            name='roll',
            table='',
        ),
    ]
