# Generated by Django 4.2.1 on 2023-05-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('card_id', models.CharField(max_length=8, null=True, unique=True, verbose_name='学工号')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='邮箱')),
                ('date_of_birth', models.DateField(null=True, verbose_name='出生日期')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='电话号码')),
                ('category', models.CharField(max_length=20, null=True, verbose_name='专业领域')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='照片')),
                ('introduction', models.TextField(null=True, verbose_name='简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在线')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否能管理数据')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='是否老师')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '所有用户',
            },
        ),
    ]
