<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-05-16 12:27
=======
# Generated by Django 4.2.1 on 2023-05-28 22:13
>>>>>>> master

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='card_id',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='学工号'),
        ),
    ]
