# Generated by Django 3.2.15 on 2023-01-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230113_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '所有用户'},
        ),
    ]
