# Generated by Django 4.2.1 on 2023-05-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_myuser_card_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
