# Generated by Django 3.2.15 on 2023-01-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_myuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='card_id',
            field=models.CharField(default='000000', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
