# Generated by Django 4.2.1 on 2023-05-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_myuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '所有用户'},
        ),
    ]
