# Generated by Django 3.2.18 on 2023-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_myteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteacher',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
