# Generated by Django 3.2.18 on 2023-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_myteacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteacher',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
