# Generated by Django 3.2.18 on 2023-04-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_myteacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteacher',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
