# Generated by Django 3.2.18 on 2023-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_myteacher_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteacher',
            name='card_id',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
