# Generated by Django 3.2.18 on 2023-04-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_myteacher_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteacher',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
