# Generated by Django 3.2.18 on 2023-04-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_myteacher_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myteacher',
            old_name='catagory',
            new_name='categoty',
        ),
    ]
