# Generated by Django 3.2.18 on 2023-04-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_rename_catagory_myteacher_categoty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myteacher',
            old_name='categoty',
            new_name='category',
        ),
    ]
