# Generated by Django 3.2.18 on 2023-04-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_rename_categoty_myteacher_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteacher',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
