# Generated by Django 3.2.18 on 2023-04-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_myteacher_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteacher',
            name='card_id',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='卡号'),
        ),
        migrations.AlterField(
            model_name='myteacher',
            name='category',
            field=models.CharField(max_length=20, null=True, verbose_name='专业领域'),
        ),
        migrations.AlterField(
            model_name='myteacher',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='myteacher',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='myteacher',
            name='introduction',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='myteacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否在线'),
        ),
        migrations.AlterField(
            model_name='myteacher',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否为管理员'),
        ),
        migrations.AlterField(
            model_name='myteacher',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='myteacher',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='myteacher',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='card_id',
            field=models.CharField(max_length=6, unique=True, verbose_name='卡号'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否在线'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否为管理员'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='用户名'),
        ),
    ]
