# Generated by Django 3.2.18 on 2023-04-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20230416_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTeacher',
        ),
        migrations.AddField(
            model_name='myuser',
            name='category',
            field=models.CharField(max_length=20, null=True, verbose_name='专业领域'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='introduction',
            field=models.TextField(null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='是否老师'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='照片'),
        ),
    ]
