# Generated by Django 3.2.18 on 2023-04-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20230418_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='邮箱'),
        ),
    ]
