# Generated by Django 3.2.18 on 2023-04-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='card_id',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='卡号'),
        ),
    ]
