# Generated by Django 3.2.18 on 2023-04-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_myuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='card_id',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='卡号'),
        ),
    ]
