# Generated by Django 3.2.18 on 2023-04-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_alter_myuser_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=30, verbose_name='用户名'),
        ),
    ]
