# Generated by Django 3.2.18 on 2023-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='card_id',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='学工号'),
        ),
    ]
