# Generated by Django 4.2.1 on 2023-05-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='is_removed',
            field=models.BooleanField(verbose_name='是否隐式删除？（隐式删除即不显示在聊天界面中，但是保留该记录在数据库中）'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
    ]
