# Generated by Django 4.2.1 on 2023-05-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0002_alter_messagemodel_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
    ]
