# Generated by Django 4.2.1 on 2023-05-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0003_alter_messagemodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
