# Generated by Django 4.2.1 on 2023-05-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0004_alter_messagemodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='is_removed',
            field=models.BooleanField(verbose_name='是否隐式删除？（隐式删除即不显示在聊天界面中，但是保留该记录在数据库中）'),
        ),
    ]
