# Generated by Django 4.2.1 on 2023-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat2', '0005_alter_messagemodel_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
