# Generated by Django 3.2.15 on 2023-01-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.CharField(choices=[(1, 'Manager'), (2, 'Teacher'), (3, 'Student')], default='Student', max_length=32),
        ),
    ]
