# Generated by Django 3.2.15 on 2023-01-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_person_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.CharField(choices=[('Manager', '管理员'), ('Teacher', '教师'), ('Student', '学生')], default='学生', max_length=32),
        ),
    ]
