# Generated by Django 3.2.15 on 2023-01-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_person_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '用户', 'verbose_name_plural': '所有用户'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='group',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_login',
        ),
    ]
