# Generated by Django 3.2.18 on 2023-04-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteacher',
            name='phone',
            field=models.CharField(default=12345678901, max_length=11),
            preserve_default=False,
        ),
    ]
