# Generated by Django 3.2.18 on 2023-04-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_myteacher_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTeacher',
        ),
    ]
